version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: gmt2001/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=America/New_York
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/pyouroboros/hooks:/app/pyouroboros/hooks
