version: "3"
services:
  ouroboros:
    container_name: ouroboros
    image: thisismental/ouroboros:latest
    restart: unless-stopped
    environment:
      - PUID=100
      - PGID=100
      - TZ=Europe/Paris
      - CLEANUP=true
      - CLEANUP_UNUSED_VOLUMES=true
      - INTERVAL=86400
      - LOG_LEVEL=info
      - SELF_UPDATE=false
      - LATEST=true
      - IGNORE=vpn
      - SKIP_STARTUP_NOTIFICATIONS=false
      - NOTIFIERS=discord://hook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
